services:
  # Apache Kafka and ZooKeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    depends_on:
      - zookeeper
  # Apache NiFi
  nifi:
    image: apache/nifi:1.22.0
    container_name: nifi
    ports:
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_SENSITIVE_PROPS_KEY=warehouse_digital_twin
    volumes:
      - ./nifi_flows:/opt/nifi/nifi-current/conf/flow
    depends_on:
      - kafka
  # Sensor Simulator
  sensor-simulator:
    build: 
      context: ./sensor_simulator
    container_name: sensor-simulator
    depends_on:
      - kafka
    restart: always
    environment:
      - KAFKA_BROKER=kafka:9092
  # Dashboard Application
  dashboard:
    build:
      context: ./dashboard
    container_name: dashboard
    ports:
      - "5000:5000"
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      
  # Machine Learning Anomaly Detection
  ml-detector:
    build:
      context: ./machine_learning
    container_name: ml-detector
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
    volumes:
      - ./machine_learning/models:/app/models
      - ./machine_learning/data:/app/data
